### ISSUE TITLE
Multiple dataset requests are being aborted prematurely

### ISSUE THREAD

**Issue by jonschwenk** [VeinsOfTheEarth/rabpro#103]
If a user requests multiple datasets in a call to `subbasin_stats.main()`, the return statements prevent any looping beyond the first dataset. I opened a new branch (`multiple_dataset_bugfix`) and committed the fix for this. However, it will likely break testing, so @jsta please take a look and fix tests where appropriate.

The main difference is that the return of `subbasin_stats.main()` was previously two objects, now it is two lists regardless of the number of datasets. The length of the lists is equal to the number of datasets requested.

**Comment by jsta** [comment]
FYI, I don't see a huge benefit to having this current behavior (internal looping instead of external looping). Current behavior still produces `N` GEE requests and `N` GDrive files where `N` is the number of `Dataset`(s). Perhaps there could be an actual efficiency gain if we moved the looping to be **even more internal** to the code that calls the actual GEE `map`ping.

**Comment by jonschwenk** [comment]
Good point, I guess that at least now we're prepared for moving the call more internally.
