### ISSUE TITLE
JOSS review : Create zenodo entry for hydro basins file

### ISSUE THREAD

**Issue by kanishkan91** [VeinsOfTheEarth/rabpro#125]
Currently in the repository, specifically the data instructions- (https://veinsoftheearth.github.io/rabpro/examples/notebooks/downloading_data.html#Download-HydroBasins)

, you are provoding a link to a google drive link to download the Hydrobasins file. This is a bit arbitrary. Please put this on zenodo so there is an archived/minted version of this file. It will also automatically control for versioning. 

https://github.com/openjournals/joss-reviews/issues/4237

**Comment by jonschwenk** [comment]
Hi @kanishkan91, thanks for reviewing!

HydroBASINs is hosted by its creators at https://www.hydrosheds.org/products/hydrobasins. We provided the Google Drive file only as a convenience--to make the downloading and pathing as simple as possible. I have updated the [docs ](https://veinsoftheearth.github.io/rabpro/configure/index.html#basin-delineation) to describe how to download this data from either the native provider or via the rabpro function.

(As early as a year or so ago, it was hard to find HydroBASINs data--Hydrosheds has since created a nice website that appears to host it more permanently.)
